version: "3.9"
services:
  rl-tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl-tester
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=rl-redis:6379
      - REDIS_DB=0
      - REDIS_IP_KEY_PREFIX=/rl/ip/
      - REDIS_TOKEN_KEY_PREFIX=/rl/token/
      - MAX_REQUESTS_PER_IP=2
      - TIME_PER_IP=5
      - MAX_REQUESTS_PER_TOKEN=4
      - TIME_PER_TOKEN=5
    depends_on:
      - rl-redis
    networks:
      - rl-network

  rl-redis:
    image: redis:latest
    container_name: rl-redis
    networks:
      - rl-network

networks:
  rl-network:
    driver: bridge
